name: MQTT Traffic Route Controller
version: 1.0.1.3
slug: mqtt-traffic-route-controller
description: Controls traffic routes based on MQTT messages.
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
boot: auto
options:
  MQTT_BROKER: your_mqtt_broker_address
  MQTT_TOPIC: your_mqtt_topic
  MQTT_USERNAME: mqtt_user
  MQTT_PASSWORD: your_mqtt_password
schema:
  MQTT_BROKER: str
  MQTT_TOPIC: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: str