name: MQTT Traffic Route Controller
version: 1.0.4.2
slug: mqtt-traffic-route-controller
description: Controls traffic routes based on MQTT messages.
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
boot: auto
options:
  MQTT_BROKER: 
  MQTT_TOPIC: 
  MQTT_USERNAME: 
  MQTT_PASSWORD: 
schema:
  MQTT_BROKER: str
  MQTT_TOPIC: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: str