    "name": "MQTT Traffic Route Controller"
    "version": "1.0.0"
    "slug": "mqtt-traffic-route-controller"
    "description": "Controls traffic routes based on MQTT messages."
    "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"]
    "startup": "once"
    "boot": "auto"
    "options": {
      "mqtt_broker": "your_mqtt_broker_address",
      "mqtt_topic": "your_mqtt_topic",
      "mqtt_username": "mqtt_user", 
      "mqtt_password": "your_mqtt_password" 
    }
    "schema": {
      "mqtt_broker": "str",
      "mqtt_topic": "str",
      "mqtt_username": "str",
      "mqtt_password": "str"
    }
  
